# For reference, I used this to figure out how to configure multiple services with docker compose:
# https://learn.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/multi-container-applications-docker-compose

services:
  relay-api:
    container_name: relay-api
    build:
      context: ./
      dockerfile: ./event_relay_api/Dockerfile
    ports:
      - 81:5000
    env_file:
      - .env
    depends_on:
      - rabbitmq

  scheduler:
    container_name: scheduler
    build:
      context: ./
      dockerfile: ./scheduler/Dockerfile
    ports:
      - 82:5000
    env_file:
      - .env
    depends_on:
      - rabbitmq

  satellite-activities:
    container_name: satellite-activities
    build:
      context: ./
      dockerfile: ./satellite_activities/Dockerfile
    ports:
      - 83:5000
    env_file:
      - .env
    depends_on:
      - rabbitmq

  image-management:
    container_name: image-management
    build:
      context: ./
      dockerfile: ./image_management/Dockerfile
    ports:
      - 84:5000
    env_file:
      - .env
    depends_on:
      - rabbitmq

  gs-outbound:
    container_name: gs-outbound
    build:
      context: ./
      dockerfile: ./gs_outbound/Dockerfile
    ports:
      - 85:5000
    env_file:
      - .env
    depends_on:
      - rabbitmq

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12-management
    ports:
      - 5672:5672   # this is the actual rabbitmq communication port
      - 15672:15672 # port for web interface for managing rabbitmq
